### ISSUE TITLE
Readme review

### ISSUE THREAD

**Issue by BobbyDigitalDev** [BobbyDigitalDev/Project_4-Fruit_Cart_Finder#2]
Fritzy, please take a look at my wireframes, ERD, routes and tables to see if everything makes sense.

Thanks,
Bobby

**Comment by andrewfritz86** [comment]
Looks good. A note on Bcrypt and passwords/digest- Bcrypt expects a key called `password` when creating User objects in the database. It will then convert that password into an encrypted or 'digested' password, which will be stored as a long hex string. Make sure to keep that in mind when seeding users.

**Comment by BobbyDigitalDev** [comment]
I thought the column name was supposed to be password_digest? Neel slacked a reminder a couple weeks back telling us that. Did I misinterpret something? I'll look for you tomorrow to get a deeper explanation. 

Thank you,
BLC
Handcrafted on my mobile device.

**Comment by andrewfritz86** [comment]
Yeah yeah, your table is great. The column is just as it should be. Just keep in mind that when you create users, you pass in a password key, not password_digest.
