### ISSUE TITLE
Google Maps API Sync issue

### ISSUE THREAD

**Issue by BobbyDigitalDev** [BobbyDigitalDev/Project_4-Fruit_Cart_Finder#3]
I've hit a wall getting the google map to show up. I'm following along with google's tutorial on how to get the map to show http://gmap-tutorial-101.appspot.com/mapsapi101/0. I was able to get it working on a static page but I'm getting a "google is not defined" sync issue when applying the same method in rails. 
I've changed the position of the script calls to happen below the yield. I have a suspicion that the issue is in my manifest file but I can't find what I need to put where to get it working. 
I've spent hours researching trying to get it to show but I'm obviously missing something. Red flare shot up in the air!!!

**Comment by andrewfritz86** [comment]
What static page did you get this working on? The javascript is fine, but you are calling methods on a google object that isn't defined anywhere.
